/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartRouteImport } from './routes/cart'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AccountChangePasswordRouteImport } from './routes/account.change-password'
import { Route as BooksIndexRouteImport } from './routes/books.index'
import { Route as BooksIdRouteImport } from './routes/books.$id'
import { Route as AdminBooksIndexRouteImport } from './routes/admin.books.index'
import { Route as AdminBooksNewRouteImport } from './routes/admin.books.new'
import { Route as AdminBooksIdEditRouteImport } from './routes/admin.books.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountChangePasswordRoute = AccountChangePasswordRouteImport.update({
  id: '/account/change-password',
  path: '/account/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIdRoute = BooksIdRouteImport.update({
  id: '/books/$id',
  path: '/books/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBooksIndexRoute = AdminBooksIndexRouteImport.update({
  id: '/admin/books/',
  path: '/admin/books/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBooksNewRoute = AdminBooksNewRouteImport.update({
  id: '/admin/books/new',
  path: '/admin/books/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBooksIdEditRoute = AdminBooksIdEditRouteImport.update({
  id: '/admin/books/$id/edit',
  path: '/admin/books/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/favorites': typeof FavoritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/account/change-password': typeof AccountChangePasswordRoute
  '/books/$id': typeof BooksIdRoute
  '/account/': typeof AccountIndexRoute
  '/books/': typeof BooksIndexRoute
  '/admin/books/new': typeof AdminBooksNewRoute
  '/admin/books/': typeof AdminBooksIndexRoute
  '/admin/books/$id/edit': typeof AdminBooksIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/favorites': typeof FavoritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/account/change-password': typeof AccountChangePasswordRoute
  '/books/$id': typeof BooksIdRoute
  '/account': typeof AccountIndexRoute
  '/books': typeof BooksIndexRoute
  '/admin/books/new': typeof AdminBooksNewRoute
  '/admin/books': typeof AdminBooksIndexRoute
  '/admin/books/$id/edit': typeof AdminBooksIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/favorites': typeof FavoritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/account/change-password': typeof AccountChangePasswordRoute
  '/books/$id': typeof BooksIdRoute
  '/account/': typeof AccountIndexRoute
  '/books/': typeof BooksIndexRoute
  '/admin/books/new': typeof AdminBooksNewRoute
  '/admin/books/': typeof AdminBooksIndexRoute
  '/admin/books/$id/edit': typeof AdminBooksIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/contact'
    | '/favorites'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/account/change-password'
    | '/books/$id'
    | '/account/'
    | '/books/'
    | '/admin/books/new'
    | '/admin/books/'
    | '/admin/books/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/contact'
    | '/favorites'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/account/change-password'
    | '/books/$id'
    | '/account'
    | '/books'
    | '/admin/books/new'
    | '/admin/books'
    | '/admin/books/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/contact'
    | '/favorites'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/account/change-password'
    | '/books/$id'
    | '/account/'
    | '/books/'
    | '/admin/books/new'
    | '/admin/books/'
    | '/admin/books/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  FavoritesRoute: typeof FavoritesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  AccountChangePasswordRoute: typeof AccountChangePasswordRoute
  BooksIdRoute: typeof BooksIdRoute
  AccountIndexRoute: typeof AccountIndexRoute
  BooksIndexRoute: typeof BooksIndexRoute
  AdminBooksNewRoute: typeof AdminBooksNewRoute
  AdminBooksIndexRoute: typeof AdminBooksIndexRoute
  AdminBooksIdEditRoute: typeof AdminBooksIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/change-password': {
      id: '/account/change-password'
      path: '/account/change-password'
      fullPath: '/account/change-password'
      preLoaderRoute: typeof AccountChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/': {
      id: '/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$id': {
      id: '/books/$id'
      path: '/books/$id'
      fullPath: '/books/$id'
      preLoaderRoute: typeof BooksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/books/': {
      id: '/admin/books/'
      path: '/admin/books'
      fullPath: '/admin/books/'
      preLoaderRoute: typeof AdminBooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/books/new': {
      id: '/admin/books/new'
      path: '/admin/books/new'
      fullPath: '/admin/books/new'
      preLoaderRoute: typeof AdminBooksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/books/$id/edit': {
      id: '/admin/books/$id/edit'
      path: '/admin/books/$id/edit'
      fullPath: '/admin/books/$id/edit'
      preLoaderRoute: typeof AdminBooksIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  FavoritesRoute: FavoritesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  AccountChangePasswordRoute: AccountChangePasswordRoute,
  BooksIdRoute: BooksIdRoute,
  AccountIndexRoute: AccountIndexRoute,
  BooksIndexRoute: BooksIndexRoute,
  AdminBooksNewRoute: AdminBooksNewRoute,
  AdminBooksIndexRoute: AdminBooksIndexRoute,
  AdminBooksIdEditRoute: AdminBooksIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
